from proto import CmdID

# auto-generated <3
DUMMY_MAP = {
    CmdID.GetLevelRewardTakenListCsReq: CmdID.GetLevelRewardTakenListScRsp,
    CmdID.GetRogueScoreRewardInfoCsReq: CmdID.GetRogueScoreRewardInfoScRsp,
    CmdID.QueryProductInfoCsReq: CmdID.QueryProductInfoScRsp,
    CmdID.GetQuestDataCsReq: CmdID.GetQuestDataScRsp,
    CmdID.GetQuestRecordCsReq: CmdID.GetQuestRecordScRsp,
    CmdID.GetCurAssistCsReq: CmdID.GetCurAssistScRsp,
    CmdID.GetRogueHandbookDataCsReq: CmdID.GetRogueHandbookDataScRsp,
    CmdID.GetDailyActiveInfoCsReq: CmdID.GetDailyActiveInfoScRsp,
    CmdID.GetFightActivityDataCsReq: CmdID.GetFightActivityDataScRsp,
    CmdID.GetMultipleDropInfoCsReq: CmdID.GetMultipleDropInfoScRsp,
    CmdID.GetPlayerReturnMultiDropInfoCsReq: CmdID.GetPlayerReturnMultiDropInfoScRsp,
    CmdID.GetShareDataCsReq: CmdID.GetShareDataScRsp,
    CmdID.GetTreasureDungeonActivityDataCsReq: CmdID.GetTreasureDungeonActivityDataScRsp,
    CmdID.PlayerReturnInfoQueryCsReq: CmdID.PlayerReturnInfoQueryScRsp,
    CmdID.GetPlayerBoardDataCsReq: CmdID.GetPlayerBoardDataScRsp,
    CmdID.GetActivityScheduleConfigCsReq: CmdID.GetActivityScheduleConfigScRsp,
    CmdID.GetMissionDataCsReq: CmdID.GetMissionDataScRsp,
    CmdID.GetChallengeCsReq: CmdID.GetChallengeScRsp,
    CmdID.GetCurChallengeCsReq: CmdID.GetCurChallengeScRsp,
    CmdID.GetRogueInfoCsReq: CmdID.GetRogueInfoScRsp,
    CmdID.GetExpeditionDataCsReq: CmdID.GetExpeditionDataScRsp,
    CmdID.GetJukeboxDataCsReq: CmdID.GetJukeboxDataScRsp,
    CmdID.SyncClientResVersionCsReq: CmdID.SyncClientResVersionScRsp,
    CmdID.DailyFirstMeetPamCsReq: CmdID.DailyFirstMeetPamScRsp,
    CmdID.GetMuseumInfoCsReq: CmdID.GetMuseumInfoScRsp,
    CmdID.GetLoginActivityCsReq: CmdID.GetLoginActivityScRsp,
    CmdID.GetRaidInfoCsReq: CmdID.GetRaidInfoScRsp,
    CmdID.GetTrialActivityDataCsReq: CmdID.GetTrialActivityDataScRsp,
    CmdID.GetBoxingClubInfoCsReq: CmdID.GetBoxingClubInfoScRsp,
    CmdID.GetNpcStatusCsReq: CmdID.GetNpcStatusScRsp,
    CmdID.TextJoinQueryCsReq: CmdID.TextJoinQueryScRsp,
    CmdID.GetSecretKeyInfoCsReq: CmdID.GetSecretKeyInfoScRsp,
    CmdID.GetVideoVersionKeyCsReq: CmdID.GetVideoVersionKeyScRsp,
    CmdID.GetCurBattleInfoCsReq: CmdID.GetCurBattleInfoScRsp,
    CmdID.GetPhoneDataCsReq: CmdID.GetPhoneDataScRsp,
    CmdID.InteractPropCsReq: CmdID.InteractPropScRsp,
    CmdID.FinishTalkMissionCsReq: CmdID.FinishTalkMissionScRsp,
    CmdID.GetRechargeGiftInfoCsReq: CmdID.GetRechargeGiftInfoScRsp,
}
